routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ArticlesController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Route::name('profile.')->middleware('auth')->controller(ProfileController::class)->group(function () {
//     Route::get('/profile', 'edit')->name('edit');
//     Route::patch('/profile', 'update')->name('update');
//     Route::delete('/profile', 'destroy')->name('destroy');
// });

Route::resource('profile', ProfileController::class)->only([
    'edit', 'update', 'destroy'
])->middleware('auth');

Route::controller(PagesController::class)->group(function () {
    Route::get('/contact', 'contact');
    Route::get('/about', 'about');
});

Route::get('tags/{tags}', [TagsController::class, 'show']);

Route::resource('/articles', ArticlesController::class)->except('index')->middleware('auth');

Route::get('/articles', [ArticlesController::class, 'index']);

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="{{ asset('css/output.css') }}" rel="stylesheet">
</head>

<body>
    @include('navbar')
    <div class="container">
        @include('flash::message')
        @yield('content')
    </div>
    <script src="{{ asset('js/output.js') }}"></script>
    <script>
        $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
    </script>
    @yield('footer')
</body>

</html>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    {{ __("You're logged in!") }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/articles">Articles</a>
                </li>
            </ul>

        </div>
        <ul class="navbar-nav navbar-right me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page"
                    href="{{ route('articles.show', $latest->id) }}">{{ $latest->title }}</a>
            </li>
        </ul>
    </div>
</nav>