routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ArticlesController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Route::name('profile.')->middleware('auth')->controller(ProfileController::class)->group(function () {
//     Route::get('/profile', 'edit')->name('edit');
//     Route::patch('/profile', 'update')->name('update');
//     Route::delete('/profile', 'destroy')->name('destroy');
// });

Route::resource('profile', ProfileController::class)->only([
    'edit', 'update', 'destroy'
])->middleware('auth');

Route::controller(PagesController::class)->group(function () {
    Route::get('/contact', 'contact');
    Route::get('/about', 'about');
});

Route::get('tags/{tags}', [TagsController::class, 'show']);

Route::resource('/articles', ArticlesController::class)->except('index')->middleware('auth');

Route::get('/articles', [ArticlesController::class, 'index']);

require __DIR__ . '/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'body',
        'published_at',
        'user_id',
    ];

    protected $dates = ['published_at'];

    /**
     * Scope queries to atricles that have been published.
     *
     * @param Builder $query
     * @return void
     */
    protected function scopePublished(Builder $query): void
    {
        $query->where('published_at', '<=', Carbon::now());
    }

    /**
     * Scope queries to atricles that have been unpublished.
     *
     * @param Builder $query
     * @return void
     */
    protected function scopeUnPublished(Builder $query): void
    {
        $query->where('published_at', '>', Carbon::now());
    }
    /**
     * Get and set the published_at attribute.
     *
     * @return Attribute
     */
    protected function publishedAt(): Attribute
    {
        return Attribute::make(
            get: fn ($date) => Carbon::parse($date)->format('Y-m-d'),
            set: fn ($date) => Carbon::createFromFormat('Y-m-d', $date),
        );
    }

    /**
     * An article is owned by user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * An tags is owned by articles.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Tag;
use App\Http\Requests\ArticleRequest;
use App\Services\ArticleService;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

class ArticlesController extends Controller
{

    public ArticleService $service;

    public function __construct(ArticleService $service)
    {
        $this->service = $service;
    }

    /**
     * Show all articles.
     *
     * @return View
     */
    public function index(): View
    {
        return view('articles.index')->with('articles', Article::latest('published_at')->published()->get());
    }

    /**
     * Show a single articles.
     *
     * @param Article $article
     * @return View
     */
    public function show(Article $article): View
    {
        return view('articles.show')->with('article', $article->load('tags'));
    }

    /**
     * Show create article form.
     *
     * @return View
     */
    public function create(): View
    {
        return view('articles.create')->with('tags', Tag::pluck('name', 'id'));
    }

    /**
     * Show edit article form.
     *
     * @param Article $article
     * @return View
     */
    public function edit(Article $article): View
    {
        $tags = Tag::pluck('name', 'id');
        return view('articles.edit')->with([
            'tags' => $tags,
            'article' => $article->load('tags')
        ]);
    }

    /**
     * Save a new article.
     *
     * @param ArticleRequest $request
     * @return RedirectResponse
     */
    public function store(ArticleRequest $request): RedirectResponse
    {
        $this->service->store($request->validated());
        $this->service->flashSuccess('Your article has been created');
        return redirect('articles');
    }

    /**
     * Update an article.
     *
     * @param Article $article
     * @param ArticleRequest $request
     * @return RedirectResponse
     */
    public function update(Article $article, ArticleRequest $request): RedirectResponse
    {
        $this->service->update($article, $request->validated());
        return redirect('articles');
    }
}

resources/views/articles/create.blade.php
@extends('app')

@section('content')
    <h1>Write a New Article</h1>
    <hr>
    <form action="{{ route('articles.store') }}" method="POST">
        @csrf
        @include('articles.form', ['submitButton' => 'Add Article'])
    </form>
@endsection

resources/views/articles/edit.blade.php
@extends('app')

@section('content')
    <h1>Edit: {{ $article->title }}</h1>
    <hr>
    <form action="{{ route('articles.update', $article->id) }}" method="POST">
        @csrf
        @method('patch')
        @include('articles.form', ['submitButton' => 'Update Article'])
    </form>
@endsection

resources/views/articles/form.blade.php
<div class="form-group">
    <label for="title">Title</label>
    <input value="@isset($article){{ $article->title }}@endisset" type="text" name="title"
        id="title" class="form-control">
</div>
<div class="form-group">
    <label for="body">Body</label>
    <textarea rows="10" name="body" id="body" class="form-control">
@isset($article)
{{ $article->body }}
@endisset
</textarea>
</div>
<div class="form-group">
    <label for="published_at">Publish On</label>
    <input value="@isset($article){{ $article->published_at }}@endisset" type="date"
        name="published_at" id="published_at" class="form-control">
</div>
<div class="form-group">
    <label for="tag_list">Tags</label>
    <select class="form-select" name="tags[]" id="tag_list" multiple aria-label="multiple select example">
        @foreach ($tags as $key => $tag)
            <option value="{{ $key }}"
                @isset($article)
                    {{ $article->tags->contains($key) ? ' selected' : '' }}
                @endisset>
                {{ $tag }}
            </option>
        @endforeach
    </select>
</div>

<div class="form-group mt-3">
    <button type="submit" class="btn btn-primary form-control">{{ $submitButton }}</button>
</div>

@section('footer')
    <script>
        $('#tag_list').select2({
            placeholder: 'Choose a tag',
            // tags: true,
            // ajax: {
            //     dataType: 'json',
            //     url: 'api/tags',
            //     delay: 250,
            //     data: function(params) {
            //         return {
            //             q: params.term
            //         }
            //     },
            //     processResult: function($data) {
            //         return {
            //             results: data
            //         }
            //     }
            // }
        });
    </script>
@endsection

@include('errors.list')

resources/views/articles/index.blade.php
@extends('app')

@section('content')
    <h1>Article</h1>
    @foreach ($articles as $article)
        <article>
            <h2>
                <a href="{{ route('articles.show', $article->id) }}">
                    {{ $article->title }}
                </a>
            </h2>
            <div class="body">
                {{ $article->body }}
            </div>
        </article>
    @endforeach
@endsection

resources/views/articles/show.blade.php
@extends('app')

@section('content')
    <h1>{{ $article->title }}</h1>
    <article>
        <div class="body">
            {{ $article->body }}
        </div>
    </article>

    @unless($article->tags->isEmpty())
        <h5>Tags:</h5>
        <ul>
            @foreach ($article->tags as $tag)
                <li>{{ $tag->name }}</li>
            @endforeach
        </ul>
    @endunless

@endsection